### ISSUE TITLE
Refactor code into cmdlets

### ISSUE THREAD

**Issue by iamraghavs** [raghav710/PS-docdb-utils#2]
the create docDB and create collection functions are just methods as of now. Refactor them to convert them into cmdlets

This would mainly involve 
1. Changing the name of the methods
2. Converting the methods from ScriptMethods to normal methods

**Comment by cofonseca** [comment]
I can take this one!

**Comment by iamraghavs** [comment]
Sure! go ahead. Happy hacktoberfest :)
Feel free to discuss any architectural/design decisions you would like to make as this is a fresh repo and your contributions will form its foundation :)

**Comment by cofonseca** [comment]
@raghav710 Thanks! I'll admit that I'm not really familiar with DocDB, but I'm happy to help restructure and rewrite any bits of code that you may need! I may need your help with testing in return, since I don't really have any way of testing this. :(

I managed to rewrite the first three methods as traditional functions, and refactored a few other bits and pieces. I'll submit a pull request - let me know what you think.

Thinking long-term, I think it might be helpful to split each function out into its own .ps1 file, and create a module to package them all together. Thoughts?

**Comment by iamraghavs** [comment]
@cofonseca thanks for your PR! I'll take a look at it. 
I am thinking something like an integration test utility might be helpful to test this, as of now I'll do a manual test
Yes, for the long term splitting them would be a good step forward as that is what powershell itself does
